language: ruby

rvm:
  - 2.6.5

addons:
  - postgresql

cache:
  bundler: true
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec