language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: yb8hQz5U3r1sVDsoCpzkKfpjgDjL69sUbQ5hCQWLBoqcay9GckZwzog++pSYJb1S/ZsBz9o/+wTPZkUSCgD7xFtx1qScU35Rv9NToZs284mTORFRoA2g/4AUqy1dG/FcGi3wj60oYtV+tz/V1FatMfpWG7ZtUSbGPS84uzfESfUGPPkT7DU4M2YFdbKGrxaLBK2O4lMJTSQVB+Cwlm5sVMUtoa8hhuxAHw3lv7InA5dtVVwwpOIdlDD9AEQxqBuBHR09wE7oUwHJ/pADJ96MJ8v3YNbQs49h0kfth26AkFvg3o17028Wk/G78m38B69C46IY06tFdohLJX5VOAE21Rkb+TyGIfigN7QMnsN09fN0MJDWtgbAxdGzEHbxa+Akag9i/avKq4u5fkCLj7g5BjqRXHOxL/Koxw4oR/iCYH6JHNXkUbCl/jbypNmdlkBPVZnmAmK1amLha1iPkfqA69Mg9cy9/Pb2SOY0/Zipwxer3a8NkmYmkKSAv+RMPild51WLZAMqgAlQDQHSwQV9C7mCmO7C/+i+8lOgkVbmngbkTumO2PNj8X6IbLzLDOSffzE9EJ8VuKMhyCE0Iaj/OZh1CKhavkEVAP2lziOrgJS8plNmL4zQrhXwz1VnOBGDjDq6mIawPhILxE+e42NPYL5j8BUmx2gwB7TQugelMp8=
  app: acebook-uckerbergs
  on:
    repo: Pi-hils/Acebook
