language: ruby
cache:
  bundler: true
  yarn: true
rvm:
- 2.6.5
services:
- postgresql
install:
- bundle install
- nvm install node
- npm i -g yarn
- yarn
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: O0L3iiLIiXSpRvWv6WBw8gqbRNxIkbopZCil20gWnVoH/HQ+k2u2SERfl8US7H7FIw50+CFzHNE+mulOz6IWR7k6nl4XcgOUXl9uDN5vq0u4WKx9qMknkErLBBlbUXJop2Uh7edDxpKBVAFUjpN3pQMXzFsBQ+fK/V4TuTc79wzwc68purr7/Sc/Jd1wnJ958djm0D46xOUIKwLX/7Vc5hDgR+ZEdcoP7XOE7SOATSCyRHx24hl2FzVvk7w5UYHRUsbQmekgmoL75pen5yhx4N2idxzgqJEYxqdPmqbqvHgocnkw8tNTiCPl9V6e14s7ESQXUauR70eP7e0iVXZXyH5EO8g43t/j5RGqsH8ibx+N6quwIG0sLeguoXZZmNND3fyxx6dX0AMBg6JJG+X4Uqzo6zFA5UenS9cmQq7rRf3sFDTEH6ota9CIZGyMe8fOP1wrVK7ynnFS3n/2acg+LWmHQ8dZ0a+zCBbzXqbPQ3kuh/FwaQeIUHV8J6t1U8KxMpdLWmZdG1uCdbLwVm7ryZwd/n0u0OxsB5w38krSIHUv6woW/I2UgpQdsOV8KUNGOCSGXXB+4jE932+wKTBH9MKRVGh1GxaTJxuv+8Epub0DjhekyNqCRyn3wVD3ThnqtwusG4l4fznDsdvNeZ30ZZ5eNtGzwxfZ4j1cj0Nn0g4=
  app: secure-forest-28833
  on:
    repo: Pi-hils/Acebook
